os:
- linux
sudo: false
language:
- c
- cpp
cache: ccache
addons:
  apt:
    packages:
    - cmake
    - libboost-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-test-dev
    - uuid-dev
    - libnss3-dev
    - libsasl2-dev
    - sasl2-bin
    - swig
    - python-dev
    - valgrind
    - ruby
before_install:
- export PATH=/home/travis/.local/bin:$PATH
- export PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages:$PYTHONPATH
install:
- pip install --user --upgrade pip
- pip install --user qpid-python
before_script:
- mkdir Build
- cd Build
- cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install
script:
- cmake --build . --target install && ctest -V

